#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/aj/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/aj/Desktop/RELIQ_GITHUB_TEST/reliq"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/aj/Desktop/RELIQ_GITHUB_TEST/reliq/macos/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=2.3.1"
export "FLUTTER_BUILD_NUMBER=2301"
export "DART_DEFINES=RkxVVFRFUl9CVUlMRF9OQU1FPTIuMy4x,RkxVVFRFUl9CVUlMRF9OVU1CRVI9MjMwMQ==,RkxVVFRFUl9WRVJTSU9OPTMuNDcuNg==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NWZjMzQ2ODM5Yg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NjkyMTM2Y2I2NQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy41"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=/Users/aj/Desktop/RELIQ_GITHUB_TEST/reliq/.dart_tool/package_config.json"
